repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: 'https://github.com/rtts/djhtml'
    rev: v1.4.9
    hooks:
      - id: djhtml
        entry: djhtml -t 2 -i
        language_version: python3.9
  - repo: 'https://github.com/ikamensh/flynt/'
    rev: '1.0.1'
    hooks:
      - id: flynt
        language_version: python3.9
  - repo: 'https://github.com/asottile/pyupgrade'
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        entry: pyupgrade --py3-plus --py36-plus --keep-runtime-typing
        language_version: python3.9
  - repo: 'https://github.com/psf/black'
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.9
